### PR TITLE
Fixed health check to khoj api

### PR DESCRIPTION
**Pull request by ayushjha119**
Changed @app.get("/health") to @api.get("/health")
used the Response class and set the input for for status_code to 200 and also remove the comment.

### CODE REVIEW

**Comment by ayushjha119** [comment]
@sabaimran sorry for that silly mistake, i hope now everything will work fine

**Comment by sabaimran** [comment]
No issues @ayushjha119 ! Looks good to me. By the way, you don't have to create a new PR every time you push a change! You can simply push updates to your existing branch, and the PR should update on its own.

**Comment by ayushjha119** [comment]
> No issues @ayushjha119 ! Looks good to me. By the way, you don't have to create a new PR every time you push a change! You can simply push updates to your existing branch, and the PR should update on its own.

OKK , got it but still i am getting this 
Screenshot 2023-12-22 104609

**Comment by sabaimran** [comment]
Closes #570.

**Pull request merged**
